# Site Info
title:              "张亚东 · Yarden Zhang"
description:        "The life of Mojia"
author_name:        "Yarden Zhang" # change this to your name
logo_url:           https://avatars.githubusercontent.com/u/235275721?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                http://wine.org.cn # main url
permalink:          /:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
